name: Auto Build and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev gh

      - run: make

      - run: mv fdf fdf-linux-x86_64

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=v$(date +'%Y.%m.%d.%H%M%S')

          gh release create "$VERSION" \
            ./fdf-linux-x86_64 \
            --title "$VERSION" \
            --notes "Automatic release"
