name: Build and Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev

      - name: Build
        run: make

      - name: Rename binary
        run: mv fdf fdf-linux-x86_64

      - name: Create Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: fdf-linux-x86_64
